accounts:
  - name: cryptozone
    coins: ["30000000crzs"]
validator:
  name: cryptozone
  staked: "10000000crzs"
client:
  openapi:
    path: "docs/static/openapi.yml"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "crzs"
